name: Setup lua-language-server
description: Install lua-language-server for Lua type checking

inputs:
  version:
    description: lua-language-server version
    required: false
    default: "3.13.5"

runs:
  using: composite
  steps:
    - name: Install lua-language-server
      shell: bash
      run: |
        LUALS_VERSION="${{ inputs.version }}"
        if [ "$RUNNER_OS" = "Linux" ]; then
          LUALS_TARBALL="lua-language-server-${LUALS_VERSION}-linux-x64.tar.gz"
        else
          LUALS_TARBALL="lua-language-server-${LUALS_VERSION}-darwin-arm64.tar.gz"
        fi
        curl -fsSL -o /tmp/luals.tar.gz "https://github.com/LuaLS/lua-language-server/releases/download/${LUALS_VERSION}/${LUALS_TARBALL}"
        mkdir -p "$HOME/.local/luals"
        tar -xzf /tmp/luals.tar.gz -C "$HOME/.local/luals"
        echo "$HOME/.local/luals/bin" >> "$GITHUB_PATH"
